### ISSUE TITLE
cannot use /api/ansibletaskoutput in celery 4.0

### ISSUE THREAD

**Issue by playniuniu** [trondhindenes/flansible#1]
Hi

This project is great, but I found that when I update celery to 4.0, it cannot use this /api/ansibletaskoutput

in celery 3.1.23, all api worked fine

**Comment by trondhindenes** [comment]
hm! Didn't even know about celery 4.0. I will look into it!

**Comment by trondhindenes** [comment]
Flansible should now be compatible with Celery 4.0.
