### ISSUE TITLE
Write in Mysql each calling of webservice

### ISSUE THREAD

**Issue by jjbehrend** [trondhindenes/flansible#7]
HI Trond , Im working with your flansible app , thats great! I have some questions to add some coding in the run_ansible_playbook.py . I want to write the calling in a mysql database , like an audit log of the creation of dockers.

Can you help me?

**Comment by trondhindenes** [comment]
Hi @jjbehrend , 
I'm sorry - I don't work with mysql at all. But you should be able to find sample code to inject whatever you need on stackoverflow etc.
